##################################################################################
# VPC
##################################################################################
variable "usp_aws_region" {
  type        = string
  description = "The default region to deploy"
}
variable "usp_prefix" {
  type        = string
  description = "The default project prefix"
  default = "usp"
}
variable "usp_aws_network" {
  description = "My AWS network configuration"
  type = object({
    lake_vpc_name           = string
    lake_aws_vpc_cidr       = string
    lake_aws_zones          = list(string)
    lake_private_subnets    = list(string)
    lake_public_subnets     = list(string)
    lake_database_subnets   = list(string)
  })
}
#variable "usp_deploy_env" {
#  type = string
#}
variable "usp_s3_env" {
  type = string
}
###################################################################
# Access keys
###################################################################
variable "usp_aws_access_key"{
  type = string
  default = ""
}
variable "usp_aws_secret_key"{
  type = string
  default = ""
}
###################################################################
# Security Group
###################################################################
variable "egress_cidr" {
  description = "List of egress rules to create where 'cidr_blocks' is used"
  type        = list(map(string))
  default     = []
}
variable "ingress_cidr" {
  description = "List of egress rules to create where 'cidr_blocks' is used"
  type        = list(map(string))
  default     = []
}
variable "default_security_group_ingress" {
  description = "List of maps of ingress rules to set on the default security group"
  type        = list(map(string))
  default     = []
}
variable "default_security_group_egress" {
  description = "List of maps of ingress rules to set on the default security group"
  type        = list(map(string))
  default     = []
}
##################################################################################
# TAGS
##################################################################################
variable "common_tags" {
  type        = map(string)
  description = "The common tags for any resource"
}
#variable "devops_workspace_tags" {
#  type        = map(string)
#  description = "The common tags for any resource"
#}
variable "vpc_tags" {
  type        = map(string)
  description = "The vpc tags"
}
variable "env_lifecycle_tags" {
  type        = map(string)
  description = "The Env lifecycle "
}
variable "iam_tags" {
  type        = map(string)
  description = "The vpc tags"
}
###################################################################
# Test Instance
###################################################################
#variable "test_instance_ami" {
#  type        = string
#  description = "Test Instance AMI"
#}
#variable "test_instance_name" {
#  type        = string
#  description = "Test Instance Name"
#}
#variable "test_instance_type" {
#  type        = string
#  description = "Test Instance type"
#}
#variable "key_name" {
#  type        = string
#  description = "Key-pair generated by Terraform"
#}
###################################################################
# Athena S3
###################################################################
variable "athena_bucket_name" {
  type = string
}
variable "athena_s3_tags" {
  type = map(string)
}
variable "usp_athena_database_name" {
  type = string
}
###################################################################
# Glue S3
###################################################################
variable "aws_cloudwatch_log_group" {
    type =  string
    default = "usp_found_to_raw"
}
variable "glue_data_catalog_db" {
    type =  string
    default = "usp-dev"
}
variable "glue_s3_tags" {
  type = map(string)
}
variable "glue_source_bucket_name" {
  type = string
}
variable "glue_destination_bucket_name" {
  type = string
}
###################################################################
# SSM Parameter
###################################################################
#variable "ssm_store_name" {
#  type = string
#}
#variable "ssm_store_password" {
#  type = string
#}
###################################################################
# S3 Bucket
###################################################################
variable "s3_usp_foundation_data" {
  type = string
}
variable "s3_usp_src_data" {
  type = string
}
variable "s3_usp_stg_data" {
  type = string
}
variable "s3_usp_curated_data" {
  type = string
}
###################################################################
# Databricks
###################################################################
#variable "databricks_cluster_name" {
#  type = string
#}

#variable "databricks_account_id" {
#  type = string
#}

#variable "databricks_account_username" {
#  type = string
#}

#variable "databricks_account_password" {
#  type = string
#}
###################################################################
# Route 53
###################################################################
#variable "r53_domain" {
#  type = string
#}
 