image: hashicorp/terraform:1.0.0

pipelines:
  branches:
    develop:
      - step:
          name: Terraform Plan
          script:
            - cd terraform/environments/dev
            - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=dev/terraform.tfstate"
            - terraform plan -out=tfplan
          artifacts:
            - terraform/environments/dev/tfplan
      - step:
          name: Manual Approval
          trigger: manual
      - step:
          name: Terraform Apply
          script:
            - cd terraform/environments/dev
            - terraform apply -auto-approve tfplan

    test:
      - step:
          name: Terraform Plan
          script:
            - cd terraform/environments/test
            - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=test/terraform.tfstate"
            - terraform plan -out=tfplan
          artifacts:
            - terraform/environments/test/tfplan
      - step:
          name: Manual Approval
          trigger: manual
      - step:
          name: Terraform Apply
          script:
            - cd terraform/environments/test
            - terraform apply -auto-approve tfplan

    master:
      - step:
          name: Terraform Plan
          script:
            - cd terraform/environments/prod
            - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=prod/terraform.tfstate"
            - terraform plan -out=tfplan
          artifacts:
            - terraform/environments/prod/tfplan
      - step:
          name: Manual Approval
          trigger: manual
      - step:
          name: Terraform Apply
          script:
            - cd terraform/environments/prod
            - terraform apply -auto-approve tfplan

definitions:
  services:
    aws:
      image: amazon/aws-cli
      variables:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION

  caches:
    terraform: ~/.terraform 